In [ ]:
!git clone https://github.com/e9t/nsmc/

Cloning into 'nsmc'...
remote: Enumerating objects: 14763, done.
remote: Counting objects: 100% (14762/14762), done.
remote: Compressing objects: 100% (13012/13012), done.
remote: Total 14763 (delta 1748), reused 14762 (delta 1748), pack-reused 1
Receiving objects: 100% (14763/14763), 56.19 MiB | 7.93 MiB/s, done.
Resolving deltas: 100% (1748/1748), done.
Updating files: 100% (14737/14737), done.


In [ ]:
!pip install konlpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 39.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 27.3 MB/s eta 0:00:00


In [ ]:
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git
%cd Mecab-ko-for-Google-Colab
!bash install_mecab-ko_on_colab_light_220429.sh

Cloning into 'Mecab-ko-for-Google-Colab'...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 138 (delta 26), reused 22 (delta 8), pack-reused 91
Receiving objects: 100% (138/138), 1.72 MiB | 6.81 MiB/s, done.
Resolving deltas: 100% (65/65), done.
/content/Mecab-ko-for-Google-Colab
Installing konlpy.....
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2024-08-10 16:31:02--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.137.23, 104.192.137.21, 104.192.137.22, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.137.23|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?response-content-disposition=attach

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
result= le.fit_transform(["개","강아지","호랑이","개","고양이"])
result

array([1, 0, 3, 1, 2])

In [ ]:
import pandas as pd # csv 로드
from sklearn.model_selection import train_test_split # data 8:2
from sklearn.preprocessing import LabelEncoder # 텍스트 -> 숫자형 바꿀때
from torchtext.data.utils import get_tokenizer # 토크나이저
from torchtext.vocab import build_vocab_from_iterator # 단어사전
 # 단어사전
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import accuracy_score
import warnings
import torchtext

/usr/local/lib/python3.10/dist-packages/torchtext/data/__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
/usr/local/lib/python3.10/dist-packages/torchtext/vocab/__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
/usr/local/lib/python3.10/dist-packages/torchtext/utils.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated

In [ ]:
# torchtext deprecation warning 무시
torchtext.disable_torchtext_deprecation_warning()

In [ ]:
# 데이터 로딩
df = pd.read_csv('/content/nsmc/ratings_train.txt', delimiter='\t')
df.columns = ['id', 'document', 'label']

In [ ]:
df

id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        150000 non-null  int64 
 1   document  149995 non-null  object
 2   label     150000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 3.4+ MB


In [ ]:
# NaN 값을 빈 문자열로 변환
df['document'] = df['document'].astype(str)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        150000 non-null  int64 
 1   document  150000 non-null  object
 2   label     150000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 3.4+ MB


In [ ]:
# 데이터 분할
train_df, valid_df = train_test_split(df, test_size=0.2, shuffle=True, random_state=42)
train_df

id                                           document  label
104025   7757635                                       나의 티모를 더럽히지마      0
5415     9554776  배비장전을 독특하게 각색한 의외로 재미있게 본 영화. 배우들의 연기력과 사극톤이 부...      1
75612    9623284  아기와의 교감도 없어 보이는 미혼모란 탈을 쓴 여자주인공의 행태가 문제인 드라마. ...      0
138169  10162069  아무 생각없이 평점 안보고 영화를 보다가 마지막 엔딩에서 소름 돋는걸 느끼는 내모습...      1
87184    8472187                              혼자서 다 할거면 제자는 왜 키우는가.      0
...          ...                                                ...    ...
119879   4992047       아...뭐이런 ㅄ영화가 다있지? 미치겠다 돈이랑시간이너무아까워서ㅠㅠ개허접졸작ㅡㅡ      0
103694   6402958                       유재석없었으면 0점인데 유재석때문에 1점이라도 준다      0
131932   5781720          아 ...장난함? ㅡ,ㅡ영화만든뜻은 알겠는데 제발 이렇게 영화 만들지 말자      0
146867   9838001                                 세월이 흘러도 명작은 명작이다!!      1
121958   3914485                             명바긔가 이거 본다는데 뭘 알고는 볼까나      1

[120000 rows x 3 columns]

In [ ]:
from konlpy.tag import Mecab
from torchtext.data.utils import get_tokenizer

mecab = Mecab()

def custom_tokenizer(text):
  return mecab.morphs(text)

In [ ]:
# 유지보수용
tokenizer = get_tokenizer(custom_tokenizer)

In [ ]:
def yield_tokens(data_iter):
  for text in data_iter:
    yield tokenizer(text)

vocab = build_vocab_from_iterator(yield_tokens(df['document']), specials=['<unk>'])

vocab.set_default_index(vocab['<unk>'])

In [ ]:
vocab.get_stoi()

{'￣∇￣)': 54044,
 '＾＾': 54041,
 '！！！': 54038,
 '律': 54036,
 '힛처': 54029,
 '힘준': 54028,
 '힘써서': 54025,
 '힘든가': 54022,
 '힘내기': 54021,
 '힘겨웠': 54020,
 '힘겨워': 54019,
 '힐신': 54017,
 '힐러리스웽크': 54016,
 '힉콕스': 54012,
 '히히히히히': 54010,
 '히포크라테스': 54008,
 '히치': 54005,
 '히지': 54004,
 '히죽히죽': 54003,
 '히잉': 54001,
 '히스토리': 53998,
 '히사코': 53997,
 '히브리': 53994,
 '히무로': 53992,
 '히메나': 53990,
 '히마': 53989,
 '히로시마': 53987,
 '히로미': 53985,
 '히뜩': 53983,
 '히나': 53979,
 '흳': 53978,
 '흰개': 53976,
 '희재': 53975,
 '희기': 53965,
 '희곡': 53964,
 '흩어져서': 53959,
 '흩뿌렸': 53957,
 '흥겨워서': 53948,
 '흥건': 53947,
 '흠좀무': 53946,
 '흙모래': 53943,
 '흘쩍': 53942,
 '흘러야': 53938,
 '흘러버렸': 53937,
 '흘러내리': 53935,
 '흘러나왔': 53934,
 '흘러나와': 53933,
 '흘깃': 53931,
 '흔했': 53930,
 '흔해져서': 53929,
 '흔해빠졌': 53928,
 '흔한데': 53927,
 '흔쾌히': 53926,
 '흔쾌': 53925,
 '흔이': 53924,
 '흑흑흑흑': 53920,
 '흑적색': 53917,
 '흑암': 53914,
 '흐흐흐흐': 53907,
 '흐트림': 53906,
 '흐트러': 53904,
 '흐엉': 53903,
 '흐린다는': 53901,
 '흐른다는': 53897,
 '흐륵': 53896,
 '흐드러지': 53894,
 '흐느적거리': 53

In [ ]:
vocab(tokenizer("▩"))

[0]

In [ ]:
torch.tensor(vocab(tokenizer("안녕 나는 자연어 처리 개발중이야")))

tensor([3100,   27,    3,    0, 2714, 3243,  110,    2,  121])

In [ ]:
# 데이터셋 클래스 : 데이터를 불러오거나 정의, 전처리하는 클래스함수
# 유지보수
class ReviewDataset(Dataset):
  def __init__(self, dataframe, vocab, tokenizer):
    self.data = dataframe # 데이터
    self.vocab = vocab # 단어리스트를 보캡의 인덱스 이용해서 숫자로 컨버팅
    self.tokenizer = tokenizer # mecab morphs 단어단위로 자르는

  def __len__(self):
    return len(self.data)

  def __getitem__(self, idx): # 데이터를 불러올 때 반응하는 함수 argument로
                              #몇 번째 데이터를 불러올건지 인덱스를 받음
    text = self.data.iloc[idx]['document'] # 받은 행 인덱스 (몇번째 데이터)로 데이터 선택
    label = self.data.iloc[idx]['label'] # 받은 행 인덱스 (몇 번째 데이터)로 정답 선택
    tokenized_text = self.tokenizer(text) # 단어 쪼개는 것
    numerical_text = torch.tensor(self.vocab(tokenized_text))
    return numerical_text, torch.tensor(label)

In [ ]:
train_dataset = ReviewDataset(train_df, vocab, tokenizer)
valid_dataset = ReviewDataset(valid_df, vocab, tokenizer)

In [ ]:
import torch

sequence_batch = [
    torch.tensor([1,2,3]),
    torch.tensor([1,2,]),
    torch.tensor([1])
]
torch.nn.utils.rnn.pad_sequence(sequence_batch, batch_first=True)

tensor([[1, 2, 3],
        [1, 2, 0],
        [1, 0, 0]])

In [ ]:
def collate_fn(batch): # 콜백함수
  texts, labels = zip(*batch)
  texts = torch.nn.utils.rnn.pad_sequence(texts, batch_first=True)
  labels = torch.stack(labels)

  return texts, labels

train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True, collate_fn=collate_fn)
valid_loader = DataLoader(valid_dataset, batch_size=2, collate_fn=collate_fn)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score

# RNN 모델 정의
class RNNClassifier(nn.Module):
  def __init__(self, vocab_size, embed_size, hidden_size, num_layers=1):
    super(RNNClassifier, self).__init__()
    self.embedding = nn.Embedding(vocab_size, embed_size)
    self.rnn = nn.RNN(embed_size, hidden_size, num_layers, batch_first=True)
    self.fc = nn.Linear(hidden_size, 1) # 이진분류를 위해 output_size를 1로 설정

  def forward(self,x):
    x = self.embedding(x)
    h, _ = self.rnn(x)
    out = self.fc(h[:, -1, :])
    return out

In [ ]:
# 하이퍼파라미터 설정
embed_size = 100
hidden_size = 128
output_size = 1
num_layers = 1
learning_rate = 0.001
num_epochs = 5

# 모델, 손실함수, 옵티마이저 초기화
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = RNNClassifier(len(vocab), embed_size, hidden_size, num_layers).to(device)
criterion = nn.BCEWithLogitsLoss() # 이진 분류를 위한 손실함수
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
# 훈련 함수
def train():
  model.train()
  for epoch in range(num_epochs):
    total_loss = 0
    for inputs, labels in train_loader:
      inputs, labels = inputs.to(device), labels.to(device, dtype=torch.float) # 레이블을 float으로 변환
      optimizer.zero_grad()
      outputs = model(inputs).squeeze() # 차원축소
      loss = criterion(outputs, labels)
      loss.backward()
      optimizer.step()
      total_loss += loss.item()
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss/len(train_loader):.4f}')

# 검증 함수
def evaluate(loader):
  model.eval()
  all_labels = []
  all_preds = []
  with torch.no_grad():
    for inputs, labels in loader:
      inputs, labels = inputs.to(device), labels.to(device, dtype=torch.float)
      outputs = model(inputs).squeeze()
      preds = (torch.sigmoid(outputs) > 0.5).float() # sigmoid와 임계값으로 예측 변환
      all_labels.extend(labels.cpu().numpy())
      all_preds.extend(preds.cpu().numpy())
  return accuracy_score(all_labels, all_preds)

# 모델 훈련 및 검증
train()
valid_accuracy = evaluate(valid_loader)
print(f'Validation Accuracy: {valid_accuracy:.4f}')

Epoch [1/5], Loss: 0.5690
Epoch [2/5], Loss: 0.4785
Epoch [3/5], Loss: 0.4536
Epoch [4/5], Loss: 0.4312
Epoch [5/5], Loss: 0.4268
Validation Accuracy: 0.8020


In [ ]:
# 인퍼런스 예제
def infer(text):
    model.eval()
    tokenized_text = tokenizer(text)
    numerical_text = torch.tensor(vocab(tokenized_text)).unsqueeze(0).to(device)
    with torch.no_grad():
        output = model(numerical_text).squeeze()
        predicted = torch.sigmoid(output).item() > 0.5
        return int(predicted)

example_text = "아 이거 좋다"
prediction = infer(example_text)
print(f'Predicted label for "{example_text}": {prediction}')


Predicted label for "아 이거 좋다": 0
