In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x_train = torch.FloatTensor([[170], [180], [160]])
y_train = torch.FloatTensor([[65], [70], [50]])

In [6]:
print(x_train)
print(x_train.shape)

tensor([[170.],
        [180.],
        [160.]])
torch.Size([3, 1])


In [7]:
print(y_train)
print(y_train.shape)

tensor([[65.],
        [70.],
        [50.]])
torch.Size([3, 1])


In [14]:
W = torch.zeros(1, requires_grad=True)

In [15]:
b = torch.zeros(1, requires_grad=True)

In [16]:
optimizer = optim.SGD([W, b], lr=0.01)

In [18]:
epochs = 100
for epoch in range(epochs+1):
  predict = x_train * W + b
  cost = torch.mean((predict-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 10 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/100 W: 211.000, b: 1.233 Cost: 3875.000000
Epoch   10/100 W: 881990947839375370730715742208.000, b: 5176241389679591837063446528.000 Cost: inf
Epoch   20/100 W: nan, b: nan Cost: nan
Epoch   30/100 W: nan, b: nan Cost: nan
Epoch   40/100 W: nan, b: nan Cost: nan
Epoch   50/100 W: nan, b: nan Cost: nan
Epoch   60/100 W: nan, b: nan Cost: nan
Epoch   70/100 W: nan, b: nan Cost: nan
Epoch   80/100 W: nan, b: nan Cost: nan
Epoch   90/100 W: nan, b: nan Cost: nan
Epoch  100/100 W: nan, b: nan Cost: nan


In [29]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [30]:
W = torch.zeros((3, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [31]:
optimizer = optim.SGD([W, b], lr=1e-5)
nb_epochs = 20
for epoch in range(nb_epochs+1):
  predict = x_train.matmul(W)+b
  cost = torch.mean((predict-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} predict: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, predict.squeeze().detach(), cost.item() # detach는 기울기가 전파되지 않는 텐서를 만드는 것
    ))

Epoch    0/20 predict: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 predict: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 predict: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 predict: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 predict: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 predict: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 predict: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 predict: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 predict: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 predict: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 predict: tensor([153.5285, 184.48

In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [33]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [34]:
model = nn.Linear(3, 1) # y = wx + wx + wx + b

In [35]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [36]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [39]:
nb_epochs = 20
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} Cost:{:.6f}'.format(
      epoch, nb_epochs, cost.item()
  ))

Epoch    0/20 Cost:3266.682129
Epoch    1/20 Cost:1052.871338
Epoch    2/20 Cost:341.327332
Epoch    3/20 Cost:112.627197
Epoch    4/20 Cost:39.118641
Epoch    5/20 Cost:15.490489
Epoch    6/20 Cost:7.894277
Epoch    7/20 Cost:5.450967
Epoch    8/20 Cost:4.663795
Epoch    9/20 Cost:4.408919
Epoch   10/20 Cost:4.325144
Epoch   11/20 Cost:4.296419
Epoch   12/20 Cost:4.285316
Epoch   13/20 Cost:4.279927
Epoch   14/20 Cost:4.276350
Epoch   15/20 Cost:4.273330
Epoch   16/20 Cost:4.270572
Epoch   17/20 Cost:4.267843
Epoch   18/20 Cost:4.265102
Epoch   19/20 Cost:4.262420
Epoch   20/20 Cost:4.259692


In [40]:
new_var = torch.FloatTensor([[73, 80, 75]])

pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75일 때의 예측값 :', pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.1916]], grad_fn=<AddmmBackward0>)


In [41]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [42]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [46]:
class MLR(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3, 1)

  def forward(self, x):
    return self.linear(x)

In [47]:
model = MLR()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [48]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 ==0:
    print('Epoch {:4d}/{} Cost:{:.6f}'.format(
      epoch, nb_epochs, cost.item()
    ))

Epoch    0/2000 Cost:24927.478516
Epoch  100/2000 Cost:7.617393
Epoch  200/2000 Cost:7.238490
Epoch  300/2000 Cost:6.881155
Epoch  400/2000 Cost:6.543940
Epoch  500/2000 Cost:6.225609
Epoch  600/2000 Cost:5.925067
Epoch  700/2000 Cost:5.641148
Epoch  800/2000 Cost:5.372880
Epoch  900/2000 Cost:5.119243
Epoch 1000/2000 Cost:4.879385
Epoch 1100/2000 Cost:4.652467
Epoch 1200/2000 Cost:4.437716
Epoch 1300/2000 Cost:4.234413
Epoch 1400/2000 Cost:4.041892
Epoch 1500/2000 Cost:3.859434
Epoch 1600/2000 Cost:3.686539
Epoch 1700/2000 Cost:3.522568
Epoch 1800/2000 Cost:3.367075
Epoch 1900/2000 Cost:3.219555
Epoch 2000/2000 Cost:3.079511


In [49]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [50]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [51]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [52]:
dataset = TensorDataset(x_train, y_train)

In [53]:
dataloader = DataLoader(dataset, batch_size =2, shuffle=True, drop_last=False)

In [54]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [55]:
nb_epoch = 100
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train =samples
    print(x_train)
    print(y_train)
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()
    ))

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
tensor([[ 73.,  80.,  75.],
        [ 96.,  98., 100.]])
tensor([[152.],
        [196.]])
Epoch 1616/2000 Batch 2/3 Cost: 1.412971
tensor([[73., 66., 70.]])
tensor([[142.]])
Epoch 1616/2000 Batch 3/3 Cost: 0.028977
tensor([[ 89.,  91.,  80.],
        [ 96.,  98., 100.]])
tensor([[180.],
        [196.]])
Epoch 1617/2000 Batch 1/3 Cost: 0.806443
tensor([[73., 80., 75.],
        [73., 66., 70.]])
tensor([[152.],
        [142.]])
Epoch 1617/2000 Batch 2/3 Cost: 0.395012
tensor([[93., 88., 93.]])
tensor([[185.]])
Epoch 1617/2000 Batch 3/3 Cost: 0.143454
tensor([[ 96.,  98., 100.],
        [ 73.,  80.,  75.]])
tensor([[196.],
        [152.]])
Epoch 1618/2000 Batch 1/3 Cost: 0.514680
tensor([[93., 88., 93.],
        [73., 66., 70.]])
tensor([[185.],
        [142.]])
Epoch 1618/2000 Batch 2/3 Cost: 0.135365
tensor([[89., 91., 80.]])
tensor([[180.]])
Epoch 1618/2000 Batch 3/3 Cost: 1.563568
tensor([[73., 80., 75.],
        [93., 88., 93.]])
tensor([[152.],
  

In [56]:
new_var = torch.FloatTensor([[73, 80, 75]])

pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.5491]], grad_fn=<AddmmBackward0>)


In [57]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [58]:
x_train  =  torch.FloatTensor([[73,  80,  75, 88],
                               [93,  88,  93, 87],
                               [89,  91,  90, 95],
                               [96,  98,  93, 95],
                               [73,  66,  70, 77],
                               [77,  82,  75, 86],
                               [88,  75,  91, 90]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142], [151], [155]])

In [59]:
dataset = TensorDataset(x_train, y_train)

In [60]:
dataloader = DataLoader(dataset, batch_size =4, shuffle=True, drop_last=False)

In [61]:
class MLR(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(4, 1)

  def forward(self, x):
    return self.linear(x)

In [62]:
model = MLR()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [63]:
nb_epochs = 10
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} Cost:{:.6f}'.format(
      epoch, nb_epochs, cost.item()
  ))

Epoch    0/10 Cost:39976.082031
Epoch    1/10 Cost:7089.709961
Epoch    2/10 Cost:1294.477295
Epoch    3/10 Cost:273.218658
Epoch    4/10 Cost:93.226494
Epoch    5/10 Cost:61.481503
Epoch    6/10 Cost:55.860420
Epoch    7/10 Cost:54.842854
Epoch    8/10 Cost:54.636543
Epoch    9/10 Cost:54.573303
Epoch   10/10 Cost:54.535297


In [66]:
x_test = torch.FloatTensor([[82, 80, 77, 85]])
model(x_test).detach()

tensor([[159.7588]])

In [69]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [72]:
class CustomDataset(Dataset):
  def __init__(self):
    self.x_data = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])

    self.y_data = torch.FloatTensor([[152], [185], [180], [196], [142]])

  def __len__(self):
    return len(self.x_data)

  def __getitem__(self, idx):
    print(idx)
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [73]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle =True)
model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [74]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    print('데이터 다 모임!')
    x_train, y_train = samples

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost : {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()
    ))

4
3
데이터 다 모임!
Epoch    0/20 Batch 1/3 Cost : 57284.445312
1
2
데이터 다 모임!
Epoch    0/20 Batch 2/3 Cost : 20915.375000
0
데이터 다 모임!
Epoch    0/20 Batch 3/3 Cost : 3593.409424
3
4
데이터 다 모임!
Epoch    1/20 Batch 1/3 Cost : 2176.164551
1
0
데이터 다 모임!
Epoch    1/20 Batch 2/3 Cost : 671.626587
2
데이터 다 모임!
Epoch    1/20 Batch 3/3 Cost : 376.183960
3
2
데이터 다 모임!
Epoch    2/20 Batch 1/3 Cost : 74.311050
0
4
데이터 다 모임!
Epoch    2/20 Batch 2/3 Cost : 12.026067
1
데이터 다 모임!
Epoch    2/20 Batch 3/3 Cost : 14.489235
0
1
데이터 다 모임!
Epoch    3/20 Batch 1/3 Cost : 4.450107
4
3
데이터 다 모임!
Epoch    3/20 Batch 2/3 Cost : 4.858151
2
데이터 다 모임!
Epoch    3/20 Batch 3/3 Cost : 15.153353
1
4
데이터 다 모임!
Epoch    4/20 Batch 1/3 Cost : 0.754859
3
2
데이터 다 모임!
Epoch    4/20 Batch 2/3 Cost : 9.281845
0
데이터 다 모임!
Epoch    4/20 Batch 3/3 Cost : 13.183583
0
4
데이터 다 모임!
Epoch    5/20 Batch 1/3 Cost : 6.326656
3
1
데이터 다 모임!
Epoch    5/20 Batch 2/3 Cost : 2.935161
2
데이터 다 모임!
Epoch    5/20 Batch 3/3 Cost : 15.078366
4
3
데이터 다 모임!
Ep

In [75]:
import torch
import torch.nn as nn
from torch import optim
import numpy as np

In [76]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1, cache=True, as_frame=False)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:1022: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [77]:
mnist.data[0]

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

In [78]:
mnist.target[0]

'5'

In [79]:
X = mnist.data/255
y = mnist.target.astype(np.int8)

In [81]:
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

X_train = torch.Tensor(X_train)
X_test = torch.Tensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

ds_train = TensorDataset(X_train, y_train)
ds_test = TensorDataset(X_test, y_test)

loader_train = DataLoader(ds_train, batch_size = 64, shuffle = True)
loader_test = DataLoader(ds_test, batch_size=64, shuffle=False)

In [82]:
model = nn.Sequential()
model.add_module('fc1', nn.Linear(28*28*1, 100))
model.add_module('relu1', nn.ReLU())
model.add_module('fc2', nn.Linear(100, 100))
model.add_module('relu2', nn.ReLU())
model.add_module('fc3', nn.Linear(100, 10))

''' 다른방법으로 모델 짜는방법 ①
model = nn.Sequential(
    nn.Linear(28*28*1, 100), # input_layer = 784, hidden_layer1 = 100
    nn.ReLU(),
    nn.Linear(100, 100), # hidden_layer2 = 100, hidden_layer2 = 100
    nn.ReLU(),
    nn.Linear(100, 10) # hidden_layer3 = 100, output_layer = 10
)
'''

''' 다른방법으로 모델 짜는방법 ②
class MultivariateLinearRegression(nn.Module):
    def __init__(self):
        super().__init__() # nn.Module 상속, 이와 같은 코드 super(MultivariateLinearRegression, self).__init__()
        self.linear1 = nn.Linear(28*28*1, 100) # input_layer = 784, hidden_layer1 = 100
        self.activate1 = nn.ReLU()
        self.linear2 = nn.Linear(100, 100) # hidden_layer2 = 100, hidden_layer3 = 100
        self.activate2 = nn.ReLU()
        self.linear3 = nn.Linear(100, 10) # hidden_layer3 = 100, output_layer = 10

    def forward(self, x): # 순전파
        out1 = self.linear1(x)
        out2 = self.activate1(out1)
        out3 = self.linear2(out2)
        out4 = self.activate2(out3)
        out5 = self.linear3(out4)
        return out5

model = MultivariateLinearRegression()
'''

' 다른방법으로 모델 짜는방법 ②\nclass MultivariateLinearRegression(nn.Module):\n    def __init__(self):\n        super().__init__() # nn.Module 상속, 이와 같은 코드 super(MultivariateLinearRegression, self).__init__()\n        self.linear1 = nn.Linear(28*28*1, 100) # input_layer = 784, hidden_layer1 = 100\n        self.activate1 = nn.ReLU()\n        self.linear2 = nn.Linear(100, 100) # hidden_layer2 = 100, hidden_layer3 = 100\n        self.activate2 = nn.ReLU()\n        self.linear3 = nn.Linear(100, 10) # hidden_layer3 = 100, output_layer = 10\n\n    def forward(self, x): # 순전파\n        out1 = self.linear1(x)\n        out2 = self.activate1(out1)\n        out3 = self.linear2(out2)\n        out4 = self.activate2(out3)\n        out5 = self.linear3(out4)\n        return out5\n\nmodel = MultivariateLinearRegression()\n'

In [83]:
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)
for epoch in range(3):

  model.train()

  for data, targets in loader_train:
    optimizer.zero_grad()
    outputs = model(data)
    loss = loss_fn(outputs, targets)
    loss.backward()
    optimizer.step()

    model.eval()
    correct = 0

    with torch.no_grad():
      for data, targets in loader_test:
        outputs = model(data)

        _, predicted = torch.max(outputs.data, 1)
        correct += predicted.eq(targets.data.view_as(predicted)).sum()

      data_num = len(loader_test.dataset)
      print('테스트 데이터에서 예측 정확도: {}/{} ({:.0f}%)\n'.format(
          correct, data_num, 100. * correct /data_num
      ))

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
테스트 데이터에서 예측 정확도: 12960/14000 (93%)

테스트 데이터에서 예측 정확도: 12938/14000 (92%)

테스트 데이터에서 예측 정확도: 12872/14000 (92%)

테스트 데이터에서 예측 정확도: 12878/14000 (92%)

테스트 데이터에서 예측 정확도: 12918/14000 (92%)

테스트 데이터에서 예측 정확도: 12943/14000 (92%)

테스트 데이터에서 예측 정확도: 12894/14000 (92%)

테스트 데이터에서 예측 정확도: 12861/14000 (92%)

테스트 데이터에서 예측 정확도: 12809/14000 (91%)

테스트 데이터에서 예측 정확도: 12713/14000 (91%)

테스트 데이터에서 예측 정확도: 12694/14000 (91%)

테스트 데이터에서 예측 정확도: 12779/14000 (91%)

테스트 데이터에서 예측 정확도: 12894/14000 (92%)

테스트 데이터에서 예측 정확도: 12906/14000 (92%)

테스트 데이터에서 예측 정확도: 12851/14000 (92%)

테스트 데이터에서 예측 정확도: 12812/14000 (92%)

테스트 데이터에서 예측 정확도: 12807/14000 (91%)

테스트 데이터에서 예측 정확도: 12947/14000 (92%)

테스트 데이터에서 예측 정확도: 12996/14000 (93%)

테스트 데이터에서 예측 정확도: 12867/14000 (92%)

테스트 데이터에서 예측 정확도: 12642/14000 (90%)

테스트 데이터에서 예측 정확도: 12577/14000 (90%)

테스트 데이터에서 예측 정확도: 12559/14000 (90%)

테스트 데이터에서 예측 정확도: 12632/14000 (90%)

테스트 데이터에서 예측 정확도: 12833/14000 (92%)

테스트 데이터에서 예측 정확도: 12901/14000 (92%)

테스